### ISSUE TITLE
Possible sample apps for iopipe

### ISSUE THREAD

**Issue by jondegenhardt** [schveiguy/iopipe#2]
Just saw the video of the Boston meetup where you presented this library. It sounds like a natural fit for the TSV tools I've open-sourced: [tsv-utils-dlang](https://github.com/eBay/tsv-utils-dlang).

They're not exciting apps, but they are real apps doing real work. They are already fast. Run-time is dominated by IO. They mostly use byLine for input. They might be easy to try with your library, in part because each is a standalone app rather than single large application. It'd be quite impressive if plugging in your library sped them them up in a meaningful way.

The best opportunity for improvement might be the `csv2tsv` tool. It's easily the slowest of the tools. I haven't tracked down root cause, but it's almost certainly due to byte-by-byte output. The `tsv-select` tool, which is essentially `cut` with field re-ordering, is just a hair slower than GNU cut (on the latest LDC release it's faster than the benchmark I published). Improving that would be meaningful.

If you're interested in trying this I'd be game to help you with it.

**Comment by schveiguy** [comment]
Hi Jon,

I remember you from the silicon valley meetup that I remotely presented at! and maybe we met at dconf 2016? In any case, I would love to work with you on getting iopipe to enhance your utilities. At the moment, I am strapped for time, but I will contact you about this after the new year. The nice thing about collaborating is that your tools should become much faster, and that iopipe will have some real usage to play with, so win-win! I like how thorough your unit tests are, it should help with making sure iopipe supports unicode fully.

A question for you, what OSes do you support with these tools? I have not written a Windows-supported low-level stream class, but that shouldn't be too hard (I need to do it anyway).

**Comment by jondegenhardt** [comment]
Hi Steve,

Sounds great. I'll be traveling until after the new year anyway, so that timing works for me as well. I didn't know if you would remember from the Silicon Valley meetup, but I did ask questions! Not from dconf, I've never been to dconf.

As to OSes - I use and test them on linux and OS X. I don't know if anyone has ever tried using them on Windows. The only portability issue on my radar is whether newline is being handled correctly in all cases. Frankly, I've found it difficult to tell from the D documentation how to ensure newline is handled in a portable way.

Should be beneficial to both projects that there are natural benchmarks for these tools. It'd be easy to generate before and after iopipe comparison. That'd be useful if you propose a phobos addition, or if you present iopipe at dconf or elsewhere. There are also some natural external comparison points, both with traditional unix tools and also with similar functionality available in other toolkits.

Beneficial from my perspective as well. A thesis I have is that D should make writing reasonable performant software without engaging in low level programming. Having these tools compete well with other bolsters that case.

**Comment by schveiguy** [comment]
Hi @jondegenhardt, been a while since I looked at this.

I just created a fork of tsv-utils, and updated tsv-select to use iopipes, which wasn't very difficult. I added a dependency to iopipe. You'll have to clone it locally, as I have not registered with code.dlang.org yet.

I can't find how you run your benchmarks, so I figured maybe you can help with this? Given my tests with straightforward phobos byLine vs. iopipe, this should be a significant improvement.

I have not altered the output mechanism yet, but that shouldn't be too difficult. Since I haven't done any testing or optimization exactly on the output part, I wanted to see the effect of changing the input system first.

**Comment by jondegenhardt** [comment]
Fantastic! I'll give it a try this weekend (or even tonight). Won't take very long to try it out. It'll be quite impressive if tsv-select improves, it's already fast.

**Comment by jondegenhardt** [comment]
I should have an initial timing test shortly. There's a bug though - Haven't investigated fully, but it appears the newline is being retained. stdio.File.byLine has a template parameter, keepTerminator, that defaults to No, so the newline gets removed. Looks like that's not happening.

You can see this by building with dub in the root directory (dub run -- --compiler=ldc2. Then 'cd tsv-select', and 'make test-nobuild'. This runs tests against the executable and diffs against output. If you look at the diffs, you'll see that every run that asked for the last field on the line has an extra blank line, suggesting it was written out with an extra newline appended.

**Comment by jondegenhardt** [comment]
It's slower with iopipe. Baseline: 4.22 sec; iopipe: 5.66 sec

I made sure I was building with the same flags. Is iopipe decoding to dchar? That would make a difference. My baseline code avoids that, because with utf-8 input TSV delimiters are always ascii. There is decoding to dchar when necessary, for example, case insensitive string compare in tsv-filter. But tsv-select only needs to identify delimiter characters (newline and tab).

**Comment by jondegenhardt** [comment]
Tests are run against the HEPMASS data set from the UCI machine learning repository: http://archive.ics.uci.edu/ml/datasets/HEPMASS. The file is the all_train.csv.gz file from here: http://archive.ics.uci.edu/ml/machine-learning-databases/00347/

Unzip it. This file doesn't use CSV escapes, so you can run against the csv as:
```
$time tsv-select -d , -f 1,8,19 all_train.csv > /dev/null
```

Or, convert to TSV first with csv2tsv (`csv2tsv all_train.csv > all_train.tsv`) and run:
```
$time tsv-select -f 1,8,19 all_train.tsv
```

For consistent runs, warm-up any disk cache by running something `wc -l` against the target file first.

**Comment by schveiguy** [comment]
Thanks. I was expecting an easy win, but should have known it would be more challenging :)

Many reasons I can think of for the poor performance -- I only tested on dmd, so my numbers might be skewed; phobos byLine may have improved in the meantime; some unforeseen interaction between the data set and the code; cache or inlining issues; etc. I'm sure I can figure out what is happening and speed it up.

> Is iopipe decoding to dchar?

No, the byLine encodes the given dchar, and looks specifically for that sequence. It has special paths for one element, so it's not checking sequences in the hot code. But maybe still room for improvement.

> it appears the newline is being retained

Yes, iopipe byline is not the same thing as Phobos byline. It simply regulates the release of data to the downstream pipe by looking for a delimiter. It can't remove the delimiter because that's in the stream. It allows interesting things like always keeping 3 lines in context for instance.

I will make a range adapter that removes the newline.

**Comment by jondegenhardt** [comment]
Fall 2015, just as I started programming in D, there was a significant byLine speedup. Version 2.068.0.
PR: https://github.com/dlang/phobos/pull/3089
Forum: http://forum.dlang.org/thread/melpfi$2scc$1@digitalmars.com

**Comment by schveiguy** [comment]
My tests were done after that. After dconf 2016 actually.

**Comment by schveiguy** [comment]
Some update: using the latest compiler/phobos, iopipe is still faster with dmd with the test I was running (which wasn't nearly as large as yours, only about 400k lines), but only be a tiny bit. I'm downloading the test file you have now to see if I see the same results with dmd on that. If that still sees the same results, then I'll try ldc.

**Comment by schveiguy** [comment]
with dmd on your test file, iopipe is much much slower, even with dmd. I can work on this and figure out why that's happening.

**Comment by schveiguy** [comment]
@jondegenhardt I have updated iopipe. Made some really dumb errors, you can see with the last commit how they are fixed. Basically, I messed up an optimization when the buffer is an array, so was using the fallback implementation. I also improved the fallback implementation to use a local vs. looking up data from the struct.

On my simple test (basically counts lines in a file) running on your test case, I am now very close to matching the performance of Phobos, but not beating it (7 seconds for iopipe, 6.4 for Phobos). This is a bit disappointing since I was thinking my code was 2x faster. My original test case has now returned to 2x faster, but it's so small that could be due to some sort of set up that the Phobos one is doing (the times are miniscule).

Testing tsv-select I see similar results (14.4s for iopipe vs. 13.7s for Phobos). This is still with DMD, so possibly iopipe version will be better or worse compared to Phobos on ldc/gdc with its superior inlining capability.

**Comment by jondegenhardt** [comment]
Okay, I'll pull your updates and see what I get. (Can't do it right this moment, though).

Don't know if you saw the benchmarks I published a few days ago, but one curious bit is that tsv-select is quite a bit faster than GNU cut on large files, but GNU cut is faster on small files. Somewhat similar.

**Comment by jondegenhardt** [comment]
Pulled the latest and ran with LDC 1.1. Definitely faster, but still not quite matching Phobos performance.  phobos:  4.20; iopipe: 4.91.

**Comment by schveiguy** [comment]
There has to be something I'm missing. readlnimpl in Phobos copies every single line possibly twice, even with getline available. getline must be so optimized that it makes up for all those copies. Will look some more

**Comment by schveiguy** [comment]
More data: Using just getline and not phobos results in an insignificant improvement. In other words, the copying costs almost nothing. Definitely not what I expected.

**Comment by schveiguy** [comment]
OK, I now have it beating Phobos and getline: Changing the read size to 1MB instead of 8KB definitely helps. But my API doesn't allow this as a parameter to `bufferedInputSource`. I will update momentarily.

**Comment by schveiguy** [comment]
I take it back. I did something really stupid -- I forgot to make sure nothing else was consuming CPU. I disabled some other programs, and now what was once 7s is now down to ~2 seconds, and phobos and getline are both still beating iopipe.

**Comment by schveiguy** [comment]
And now, the copying is definitely having an effect -- 1.8s for straight getline, 2.1 for phobos, so a 15% effect. iopipe is still slower at 2.9s. I will figure this out.

**Comment by schveiguy** [comment]
Got it 😃 

I cheated a *bit* and looked at the source for getdelim. Discovered that it uses memchr to find the delimeter. peeked at that source, and found that it searches a word at a time instead of a byte at a time. This is why my loop is much slower.

I have updated iopipe to use memchr when available (e.g. when code unit type is char, and delimeter is one code unit). I suspect we could improve things in other ways (e.g. using simd; or similarly optimized searching for multi-byte delimeters).

New times for my test: phobos = 2.1s, getline = 1.8s, iopipe 1.1s. That's a pretty significant drop, I would expect LDC-compiled iopipe to now outperform phobos on tsv-select. On my system with dmd, it's 9.5s (iopipe) vs 10.9s (phobos).

**Comment by schveiguy** [comment]
One further note: I still need to make range adapter to remove newline.

**Comment by jondegenhardt** [comment]
Very cool! I'll give it a try.

**Comment by jondegenhardt** [comment]
Yes!! Phobos:  4.13; IOPipe: 3.22. That's with LDC 1.1.

Nice job. Looks like you've got a real win here. At least in the context of my programs, this is very impressive, as they are already beating similar tools by wide margins. The range adapter will have to operate without slowing it down of course.

A couple notes:
- I built these by putting all the iopipe files directly on the ldc command line, rather than using the dub build approach, which builds the library separately. I did this in case there was a cross module optimization ldc could apply. I'll go back and try the dub build approach see if there's a difference.
- You'll notice there are small deltas in the timing numbers I report, usually < 20ms. My machine is not completely quiet either, but I do make multiple runs every time, so I have good confidence that metrics reported together are done in equivalent circumstances.

**Comment by schveiguy** [comment]
I have a theory with the performance difference between "short" files and "long" ones. One property of your test file is that the lines are pretty long, over 700 characters for each line. An optimized search for newlines going 1 word at a time vs. one char is going to beat a straight-up byte-wise search, but doesn't negate the fact that you have to make an opaque call. With shorter lines, a for-loop beats a call to memchr. With longer lines, the memchr call's overhead is dwarfed by the speedup in the search. So my theory is that even with a large file, if it has shorter lines, then the for-loop might win.

The best of both worlds may be an inline-able implementation for searching that can do word-sized comparisons. In other words, reimplement what memchr does, and let the compiler find the most optimized path.

**Comment by jondegenhardt** [comment]
Hadn't thought of that, makes sense. I've been aware that different file shapes may affect performance. I've done some spot checks, but nothing comprehensive. Mainly, it took enough time to assemble and run a single set of benchmarks across all the competing tools I tested. But yes, the hepmass file contains doubles at written in high precision, so it has long lines even though it's only 29 columns. Another set of files I use are the google ngram files. These are large in GB size, huge number of rows/lines, but each line is short (4 columns, 3 are small integers, 1 short text field).

Having the compiler inline it make sense. Made me wonder if the compiler might be able to do this (esp LDC/LLVM). I don't know the answer, but a google search turned up a blog post that might be relevant: https://gms.tf/stdfind-and-memchr-optimizations.html

**Comment by jondegenhardt** [comment]
Ah - Just realized, there's a simple data point that can be used to help test your hypothesis: Run tsv-select against a smaller hepmass file. eg. The first 100,000 lines, or whatever number results in an approx 200-300MB file. This would preserve the per-line size characteristics. Because yes, the smaller file I tested against did have a different shape. Not as radically different as the google ngram files, but still different. I'll run this later - Have to take off for a while.

**Comment by schveiguy** [comment]
Update: added mechanism to omit delimiters for byline. Updated my branch of tsv-utils to use it.
Note: files that end in newline show an extra element. I'm not sure what the correct way to do this is, because traditionally, files that don't end in newline are flagged as errors by my editor. However, a traditional "split" of data based on a delimiter should give a blank element on such a case. Indeed in a csv row, "a,b,c," would be a 4-field row.

In any case, tsv-select complains about it.

Note that performance is still good with the new range adapter.

**Comment by schveiguy** [comment]
Thinking about it more, I need to eliminate that extra empty "row", as it worked fine before trimming the delimeter. I'll think about how I can refactor the code to do so.

**Comment by schveiguy** [comment]
Pushed a new version that fixes the last line issue.

**Comment by schveiguy** [comment]
I'm somewhat happy with the given state of things. I'm going to instrument the rest of the tsv-utils to see how they fare.

**Comment by jondegenhardt** [comment]
fyi - I was doing a bit of investigation into why csv2tsv is so slow, discovered that standard D idiom for copying a file by using File.byChunk is dramatically slower than the same algorithm using File.byLine, by 15x. See [Bug 17229](https://issues.dlang.org/show_bug.cgi?id=17229). This is unfortunate because it is given in several doc examples as the fast way to copy a file.

I tried replacing byChunk with byLine in csv2tsv. Gives a minor improvement. I'm guessing the byte-at-a-time output output approach it uses problematic, but not clear. But, may be good opportunity for IOPipe on the output side here.

A related observation - Phobos byLine is a bit restrictive in that it will not accept ubyte as the array element. When dealing with UTF-8 it's useful, for performance, to process as code point / ubyte, and avoid auto-decoding. Phobos byLine is restrictive that way. I don't want to suggest what features you choose to include in IOPipe, but if it had a mode for reading utf-8 data that avoided auto-decoding I'd find it useful.

**Comment by schveiguy** [comment]
Looking at that bug, I think it's more to do with the output than the input. And in fact, I think it's more to do with the type of the array you are outputting.

If you look at the specializations, it is not designed to properly work with `ubyte[]`, which is what `byChunk` outputs. What I *think* is happening, is that it goes into the put for the range, because `is(ElementType!(ubyte[]) : const(dchar))` is true (because you can implicitly cast a `ubyte` to a `dchar` via integer promotion (IMO, a separate mistake of the D language), even though that's not the intention of the constraint), but the static if inside the function is not true (it doesn't satisfy `isSomeString`), and so it does a foreach on the `ubyte` array *converting each `ubyte` into a `dchar` through integer promotion*, and then putting that `dchar` into the output stream. If the file is ASCII, it will work, but be god-awful slow. If the file is not ASCII, it will work, but you won't get a copy of the original file, as anything over `ubyte(127)` is going to result in a weird encoded utf-8 sequence.

I think the bug there is that `LockingTextWriter` accepts anything other than a range of `char`, `wchar`, or `dchar`.

In terms of performance, I think iopipe can beat all of it 😉 I will work on csv2tsv next.

As an interim fix, I think you can just use cast to `char[]` (which is OK for utf8, or ASCII, but not for other encodings), or use `lockingBinaryWriter` instead.

> but if it had a mode for reading utf-8 data that avoided auto-decoding I'd find it useful.

Yes, I can add this. In fact, I can generalize `byLine` into `byDelim`, that takes any number of elements (and any type of element) to use as a delimiter, and still achieve the same speed. Generic is usually better, and I can leave the `byLine` as a specialization. Really, all the work of encoding/decoding is done on the setup of the byLine pipe, everything else is just straight searching in the buffer. I will still use `memchr` when the delimiter is one byte. My buffered stream can be made into a buffered stream of any type (you can see from how I added it to tsv-select it actually defaults to a `ubyte` stream, and I put in a special casting pipe to get it to be `char`-based).

**Comment by jondegenhardt** [comment]
Ah, never considered that possibility. Thanks much for looking into this. Explains why my different attempts to speed up csv2tsv have failed.

The current algo uses byte-at-a-time output, which is a natural fit for the algo with ranges. But I also spent time working chunk-at-a-time, outputting blocks from the original input that could be output unchanged. Without performance improvement. I also tried my own internal buffering, also without improvement. Both used ubyte. That's when I went to the basic file copy to see what happened there.

I'll add some additional comments to the bug ticket. My general thought is that there should be a way to write UTF-8 without translation. There is a relatively new locking binary writer, which I've never tried. Perhaps that's what should be used. There's also the question of how to perform OS appropriate newlines, which is at minimum under-documented.

**Comment by jondegenhardt** [comment]
Note: The reason my csv2tsv unit tests with non-ascii characters work is because in the unit tests I pass in a ubyte Appender rather than a lockingTextWriter. The Appender just appends the ubyte, which is what my programs expect. I do have tests against the executable, but in this case I didn't bother to include non-ascii characters, thinking it was covered in unit tests. A reminder about test completeness. :(

**Comment by jondegenhardt** [comment]
I was fortunate and it turned out csv2tsv was actually writing using char rather than ubyte, so it wasn't corrupting data. However, I'm guessing ubyte was why my original buffering attempts to produce gains. This time, buffering correctly, a single line at a time produced performance gains, it's about twice as fast as it was. (These changes are checked in.) But I think there's still large gains to be had.

**Comment by jondegenhardt** [comment]
fyi, in case you missed it - I released a new tool that may be interesting for IOPipe: [keep-header](https://github.com/eBay/tsv-utils-dlang/blob/master/keep-header/src/keep-header.d). It does a simple thing - preserve header lines (first line) when running commands like `sort` and `grep`. It might be interesting for IOPipe because: (a) it's short; (b) it's shows up as a small but measurable performance hit (perhaps an unnecessary data copy?); (c) it manually distinguishes the stdin and file read cases in a way IOPipe might be able to abstract from user code.

Note: If you try using GNU sort with this, adjust the sort buffer size as described here: [Tips & Tricks: Sort buffer size customization](https://github.com/eBay/tsv-utils-dlang/blob/master/docs/TipsAndTricks.md#set-the-buffer-size-for-reading-from-standard-input)

**Comment by jondegenhardt** [comment]
Hey @schveiguy - A quick update. I just implemented a buffered version of `byLine`. A significant performance improvement for tsv-utils, 10-40% depending on tool and file (measured on OS X). I think you're already buffering input in IOPipe. I had to repeat your `memchr` trick to turn it into a performance win. Turns out `std.algorithm.find` will use `memchar` for a 1-byte input, so I used that.

My version: [bufferedByLine](https://github.com/eBay/tsv-utils/blob/master/common/src/tsv_utils/common/utils.d#L776)

**Comment by schveiguy** [comment]
Yep. The only annoying thing is that FILE * is already buffered! So you are wasting an extra buffer. Would still expect iopipe to perform a bit better.

**Comment by jondegenhardt** [comment]
I was wondering if `byLine` from files is being buffered. I looked through `byLine/readln` but didn't see anything indicating reading more than line at a time. Is the buffering happening in the system call?

If my buffered version is just repeating what's happening elsewhere, then where am I getting such a big gain? Bypassing an internal copy perhaps?

I will have to try plugging in iopipe again. Will likely need to build it with LTO (be nice if Dub supported that), but should be able to figure that out.

**Comment by jondegenhardt** [comment]
Okay, I can see that FILE* I/O is being buffered. I'm wondering if what I'm doing is effectively overwriting the default buffer size or buffering mode on OS X. That is, if the default buffer size is small, for example, 4096, or for some reason files are getting opened in line buffering mode. I'll have to do more investigation.

**Comment by jondegenhardt** [comment]
I think you're completely right. FILE* I/O is already fully buffered at the system level. The buffering I'm doing is likely bypassing inefficiencies in phobos and perhaps druntime.

**Comment by schveiguy** [comment]
The buffer is I think about 4096. But the issues there are:
1. There is no direct buffer access, except via special functions (i.e. gnu getline will be able to access the buffer to do what we basically can do in our buffers)
2. Everything is opaque -- no opportunity for inlining.

**Comment by schveiguy** [comment]
BTW, I went over this in my iopipe talk -- FILE * buffering is done for efficiency of reading -- because you often only want a small number of bytes at a time, it avoids doing system calls for that. But there is a lost opportunity because the buffer is inaccessible.

**Comment by jondegenhardt** [comment]
Thanks. And my apologies for not having gone back over what you've said before. I know you've described all extensively in the past. Next time I look into this I'll go for the iopipe solution. Some simple tests make it clear there is a fair bit more to be gained here.

**Comment by schveiguy** [comment]
No problem, let me know if I can help you with iopipe use. I've been tinkering with it a lot lately due to another project that I'm using it for.

**Comment by jondegenhardt** [comment]
iopipe is quite a bit faster! I'll see about publishing something that shows some deltas.

This is more an `io` library question, but how one get to `stdin`? I didn't see it in `io`, and trying to access it through `std.stdio` caused conflicts.

**Comment by schveiguy** [comment]
`io` doesn't have the standard handles, which is something I've brought up a while ago. See discussion here: https://github.com/MartinNowak/io/issues/14

You can open `io` objects via native handles. That's how I do it in my testing (Posix only currently). I think it would help if you have some insight to comment on that issue report.

**Comment by schveiguy** [comment]
So to elaborate, on Posix, you just pass in the standard handle file descriptors (0, 1, 2), and on Windows, there is a Windows system call (GetStandardHandles or something like that?).

**Comment by jondegenhardt** [comment]
That worked, thanks. I'll add a comment to [io#14](https://github.com/MartinNowak/io/issues/14). Need to figure out what my message is, but might be as simple as, this stuff simply awesome, but its going to be hard to use without at least some encapsulation of stdin/stdout/stderr.

**Comment by jondegenhardt** [comment]
I finally put together a small app that allows some simple performance test comparisons of some of the I/O features in Phobos, `iopipe`, `io`, and `tsv-utils`:  [dcat-perf](https://github.com/jondegenhardt/dcat-perf). It does a very simple thing: reads a file or standard input and writes to standard output. It does this using a method specified on the command line.

There are some benchmark results on the issues page: [Issue #1](https://github.com/jondegenhardt/dcat-perf/issues/1). The show that `iopipe` is the fastest overall input mechansim, especially on skinny files.

@schveiguy, one thing you do is check the `iopipe` calls and see if I did them correctly. Code is [here](https://github.com/jondegenhardt/dcat-perf/blob/master/source/app.d). Look for the routines: `useIopipeByLineInRawOut`, `useIopipeByLineInBufOut`, and `useIopipeByLineInIOOut`.

I'm not sure how to use `iopipe` in the output layer, I'd really like to add a test case for that. One of the tests writes to `std.io` directly, but that is really slow. I'm guessing its not meant to be used raw like that.

**Comment by jondegenhardt** [comment]
I recently wrote a new tool that might have some good samples uses for `iopipe` and possibly `io`. The tool, [tsv-split](https://github.com/eBay/tsv-utils/tree/master/tsv-split), splits input lines into multiple files. It has a couple methods:
* Splits by line count - Essentially the same as the classic Unix `split` utility.
* Split by random assignment into N files
* Split by random assignment into N files, grouped by key (sharding). The reason I wrote the tool.

The algorithms are simple enough, which is one thing that might make them attractive examples.

The split by line count might be a candidate for iopipe ring buffers. What this does is read a file and split it into multiple files based on line count. e.g. 1000 lines in every output file, or 10 million lines in every file. The implementation I used is to read a buffer at a time, then walk through writing out blocks of lines. The number of lines going to an output file might be smaller or larger than the read buffer. This sounds like the characteristics you were looking for to test ring buffers ([tsv-utils #136](https://github.com/eBay/tsv-utils/issues/136)). The other useful thing is that there are at least two good benchmark apps for comparison. GNU `split` is quite fast at this task. The other is `tsv-split` itself, which is fast, though not quite a fast as GNU split. (The version in Master is quite a bit faster than the one in the last tagged release, 1.6.0).

The random assignment cases might also be interesting. They write a lot of files in random orders, one line at a time. I was wondering if it might be a use case for the multiple output stream ("scatter") in `io`. The random assignment cases I wrote work fine, but would seem to be significant performance gain opportunities.

The functions implementing the different algos is all in the same file (`tsv-split.d`):
* [splitByLineCount](https://github.com/eBay/tsv-utils/blob/master/tsv-split/src/tsv_utils/tsv-split.d#L952)
* [splitLinesRandomly](https://github.com/eBay/tsv-utils/blob/master/tsv-split/src/tsv_utils/tsv-split.d#L952)
* [splitLinesByKey](https://github.com/eBay/tsv-utils/blob/master/tsv-split/src/tsv_utils/tsv-split.d#L877)

**Comment by schveiguy** [comment]
Thanks, I will take a look at this at some point. I am indeed looking for a use case for the ring buffer.
